name: ❓ Question
description: Ask a question or get support
title: "[QUESTION] <your question>"
labels: [question]
body:
  - type: input
    id: walg-version
    attributes:
      label: WAL-G Version
      placeholder: e.g. v2.1.55 or master
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: What is your question?
      placeholder: |
        Ask anything related to WAL-G, usage, config, etc.
    validations:
      required: true
